### PR TITLE
edit appreciation msg after solving puzzle

### PR DESCRIPTION
**Pull request by JosiasAurel**
restructure the victory UI to look like the screenshot below when it's a puzzle
image

### CODE REVIEW

**Review by grymmy — COMMENTED** [review]
My only feedback is that there seems to be many lines modified that seek outside scope of the change...  did you test the twitter and reddit flows as well as the main game w/ these changes?

**Comment by JosiasAurel** [comment]
The Reddit & Twitter flows remain unchanged and normal levels show the same victory message as before

**Comment by JosiasAurel** [comment]
hmm... the huge diff in index.html is the work of the formatted (tho I use Prettier in vscode)

**Comment by grymmy** [comment]
> hmm... the huge diff in index.html is the work of the formatter (tho I use Prettier in vscode)

I think perhaps we can let this fly as it is autoformatting be please be aware, mixing in large formatting changes that are unrelated to the PR you're working on is generally considered bad practice (hard to review what changes were actually important, more potential for causing merge conflicts, damages useful git blame history, etc) - if you really, really want to reformat code or something, you should probably do so in an independent diff - and with signoff from repo owner(s).  Personally I'd suggest turning autoformatting off on repos that you don't maintain 100% for this reason...

**Comment by JosiasAurel** [comment]
> > hmm... the huge diff in index.html is the work of the formatter (tho I use Prettier in vscode)
> 
> I think perhaps we can let this fly as it is autoformatting be please be aware, mixing in large formatting changes that are unrelated to the PR you're working on is generally considered bad practice (hard to review what changes were actually important, more potential for causing merge conflicts, damages useful git blame history, etc) - if you really, really want to reformat code or something, you should probably do so in an independent diff - and with signoff from repo owner(s). Personally I'd suggest turning autoformatting off on repos that you don't maintain 100% for this reason...

Okay, thanks. I've disabled auto-formatting so this shouldn't happen again

**Comment by grymmy** [comment]
@polytroper please review and merge if you deem appropriate

**Comment by polytroper** [comment]
Made some edits but should be good to go now

**Pull request merged**
