### PR TITLE
Added new loading screen for levels

### PR DESCRIPTION
**Pull request by Captainexpo-1**

### CODE REVIEW

**Comment by Captainexpo-1** [comment]
Implements #582

**Comment by polytroper** [comment]
This looks perfect, except that I agree with your TODO; the "Level Loading" text needs a different style. I would actually get rid of the text and just use a three-dot ••• loading animation, like `dot-flashing` here: https://codepen.io/nzbin/pen/GGrXbp

**Comment by polytroper** [comment]
Seems we have some merge conflicts? Can you resolve those plz

**Comment by polytroper** [comment]
So, I notice that when I click a level that needs to load assets, the screen fades to white, but then briefly fades back to show the map and _then_ the new loading screen fades in. Can we fix this so it fades directly to the new loading screen?

**Comment by polytroper** [comment]
This is so unbelievably close, but… now the screen jumps from "•••" to the selected level. It needs to fade from "•••" to selected level (as it does if you choose a level which requires no asset loading)

**Comment by polytroper** [comment]
Ah, but now we have introduced a new issue! The “•••” screen should _only_ appear when there are assets to lazy-load. Now they show up every time the user clicks on a level, even if all the assets are loaded already. This breaks the clean transition that we want to have as the default experience when a level is clicked; the “•••” loading indicator is only there to tell you the game isn’t frozen in the event that assets need to load

**Comment by polytroper** [comment]
IT LOOKS SO GOOD!!!!

**Pull request merged**
