### PR TITLE
New icons (#201)

### PR DESCRIPTION
**Pull request by Omay238**
Please give feedback on icons

### CODE REVIEW

**Review by camdan-me — CHANGES_REQUESTED** [review]
I like where this is headed, but personally the vibe feels a little off. What are your thoughts on going with an OSS icon pack (like heroicons or the noun project)?

**Comment by Omay238** [comment]
It would definitely be much easier. I would just like to make custom icons though. Just as practice for myself. Here's the updated sound icon. Much the same, just rounded more.
sound

**Comment by Omay238** [comment]
Alright. Spent a bit on better icons. How do they look now, @camdan-me?

**Review by camdan-me — APPROVED** [review]
Looks better. Chris and I were discussing a UI redesign and things might still change a little, but for now seems alright to me, we'll see what he thinks too

**Comment by polytroper** [comment]
Hey @Omay238, sorry to say I had to revert your changes as these icons are not ready to go yet. Please wait for my review next time, I will merge the PR.

A few things that need to be addressed:
* The map icon should maybe just be a map. It was only ever a mountain emoji because I didn't like the map emoji.
* The map icon is yuuuge in this PR
* The hint icon is tiny
* The reset button has no margin now
* The volume icon is invisible against many backgrounds
* Volume icon file looks like it was exported with a large amount of blank space at the bottom

I also just don't yet feel like these match the style of SineRider better than something we might pull from Noun Project. I am not a good enough designer to say exactly why they don't line up yet. Let's make a thread in the gamedev channel with our lead artist to get their thoughts on that

image

**Comment by polytroper** [comment]
Actually, to be honest we could really use your help on the code stuff more than icons right now. Can we table this for the moment and move you to one of those issues? We _can_ launch with the current icons (or stuff from NounProject), but we are still drowning in game-breaking issues that have to be fixed before launch.

**Pull request merged**
