### PR TITLE
Add to loading screen

### PR DESCRIPTION
**Pull request by cytronicoder**
Assists in closing #207!

### CODE REVIEW

**Comment by grymmy** [comment]
@JosiasAurel could you possibly review this code to ensure it doesn't break compatibility with the scoring service?

**Comment by JosiasAurel** [comment]
I get throw a `ScoringTimeout` on the scoring service. I think merging PR (https://github.com/JosiasAurel/sinerider-scoring/pull/14) would help

**Comment by polytroper** [comment]
Looking great. Love the new loading bar. Notes:

* Nix "SineRider is a game about love & graphing", we already say that line in the intro sequence
* Put "Built and maintained by teenagers. Version 0.5" at the bottom in a lighter font, and make that link to the github
* Instead of a link to "Leaderboard", we need text saying "New puzzles every day" with clickable reddit/twitter logos that take you to the subreddit/twitterbot

**Comment by cytronicoder** [comment]
I'll go fix!

**Comment by cytronicoder** [comment]
The thing is still bugged with the link click issue.

**Comment by polytroper** [comment]
Can we get the "built+maintained by" stuff at the very bottom of the screen, and in an even subtler font?

Let's also try putting the "New puzzles" line  at the bottom of the page, just above the Built By line, formatted like this (with the alien and bird emojis standing in for logos):
"New puzzles published daily on 👽 🐦"

Remove the dotted border, and hide the "Loading x%" text since it's redundant with the loading bar

**Comment by polytroper** [comment]
Also, no underline on "New puzzles every day" since it's not a link

**Comment by cytronicoder** [comment]
Modified!

**Comment by polytroper** [comment]
image

This looks weird. I would just get rid of the red box when loading is complete, plain black underlined text is fine ^

Also the logos should be on the same line as "New puzzles published daily on". And the "Built by" line needs to be fixed so it doesn't break on the version number

**Comment by cytronicoder** [comment]
Weird... it shows as one line on mine.
Screenshot 2023-04-29 at 11 50 17 AM

**Comment by cytronicoder** [comment]
See if this works ^

**Comment by polytroper** [comment]
looks awesome. My one final request is let's put this image just above the loading bar

loading

**Comment by cytronicoder** [comment]
Is that already in the repository somewhere?

**Comment by polytroper** [comment]
Nope I just created it. You’ll have to add it to assets/images

**Comment by polytroper** [comment]
hooraaaay

**Pull request merged**
