### PR TITLE
Replace emoji with icons

### LINKED ISSUE #201: [FEATURE] Replace Emoji with Public Domain/Liscenced Icons
### Description

Emoji look aesthetically out of place and don't fully render right on all browsers (see screenshot below). Should be replaced with Icon.

### Screenshots

Screenshot 2023-03-14 at 12 39 52 PM
Screenshot 2023-03-14 at 12 41 00 PM

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by agentblack6000**
Fix #201, replace emoji with [fontawsome icons](https://fontawesome.com/search)

### CODE REVIEW

**Comment by polytroper** [comment]
mmmm these icons don't really fit the vibe. This is a good icon set for a modern webapp but we need something a bit more colorful and not so abstract.

Also files should be directly included rather than linked with a tag.

Some map icons that are more game-like, for reference:

image

image

**Comment by agentblack6000** [comment]
Would this icon be okay? It's the svg version of the emoji we currently have:
snow-capped-mountain

Also I think the music icon is okay(it's pretty standard for all apps), and I'm searching for a colorful lightbulb right now

**Comment by polytroper** [comment]
The mountain is cool but honestly I think it just needs to be a map. And it needs to sit nicely on a white BG, which that SVG would not.

**Comment by alhardwarehyde** [comment]
@agentblack6000 did you see Chris's notes Above?

**Comment by agentblack6000** [comment]
> @agentblack6000 did you see Chris's notes Above?

yep, still working on those icons

**Comment by alhardwarehyde** [comment]
@agentblack6000 we're really getting down to the wire here, any update on those icons?

**Comment by cytronicoder** [comment]
Sup @polytroper, are there any other design specs that you would recommend other than
>  This is a good icon set for a modern webapp but we need something a bit more colorful and not so abstract.

cc. @camdan-me

**Comment by polytroper** [comment]
We still do need to do this… but closing this particular PR as it is stagnant

**Pull request closed without merging**
