### PR TITLE
Support faster-than-realtime simulation and fully decouple framerate from tickrate

### PR DESCRIPTION
**Pull request by grymmy**
Decouples main::tickDelta from main::ticksPerSecond, and decouples main::requestDraw from main::tick.  This has ramifications to the sinerider scoring service which would ideally be able to score and record video of sinerider sessions in faster-than-realtime.

### CODE REVIEW

**Comment by grymmy** [comment]
This change allows for faster-than-realtime play as exhibited in this video:

https://user-images.githubusercontent.com/43505167/227064773-da6ba220-c233-4775-adf9-885b07ed14a9.mov

**Comment by grymmy** [comment]
Also to note - increasing the draw timer can produce predictable results with lower framerate:

https://user-images.githubusercontent.com/43505167/227065332-6a0e1eff-95ac-4df9-99fa-217af7b135f2.mov

**Comment by polytroper** [comment]
This looks like it would technically work, but something feels… weird about `setInterval(requestDraw, 0)`. Like it works for the wrong reasons. We want to tick as fast as we can, and guarantee one frame per tick. So I would have `setInterval(tick, 0)` and a synchronous call to `draw` at the end of `tick`—not `requestDraw`, this frame is a demand!

I would also strongly consider doing all this within `Engine.js`, which wraps up all this kind of functionality. It's not used in `main.js` right now but it should be. Integrating this abstraction will have specific benefits for this server recording stuff. I would be very happy to call about this tomorrow.

**Comment by grymmy** [comment]
@polytroper I will resolve the code duplication between main.js <> engine.js as part of this PR.

On the subject of the binding of drawing to the game tick rate, my intuition here is that long-term this is not a win necessarily...  Isn't it true that we could support higher framerates by keeping them separate?  To me, this is similar to the dynamic between FixedUpdate (representing our game logic ticks) and Update (where we draw) in Unity...  We may only update our actual object positions in the game ticks, but we could do interpolation of current positions -> target positions in the drawing code to get things more liquid-smooth (not sure if this is done now, but couldn't it be?  Correct me if I'm mistaken here plz!)

Also, for the purpose of scoring efficiently, we don't even necessarily need to draw at all, right?  This also makes me wonder about forcing draws from ticks...

**Comment by polytroper** [comment]
I don't see why it would support theoretically higher framerates. The two loops would only be directly coupled (as in one synchronously calls the other) in the case of recording, where we do actually want a 1:1 mapping of ticks to draws. During normal gameplay we would call `requestDraw` at the end of `tick` (as we do now). In the event that we don't want to render, we simply don't call `draw` _or_ `requestDraw`.

**Comment by grymmy** [comment]
@polytroper Per our discussion in slack, here's my plan forward with this PR:

1. I will move a bunch of the logic currently in main.js -> engine, and use engine from main.js
2. I will keep the ticks separate from the drawing to enabling unlocking higher framerates in the future
3. I will have a separately scheduled fast-looping timer w/ a concept similar to Unity's Update() with a deltaTime calculated and globally accessible, and that dispatches method calls to all entities for purposes of them doing draw updates between ticks, afterwards calling requestDraw() (this will be skeletonized if not implemented in its entirety)

**Comment by polytroper** [comment]
Sounds good to me.

**Comment by polytroper** [comment]
Actually SineRider deliberately does not use prototypal inheritance anywhere (note that there zero instances of `this.` in the codebase). All the OOP is done with Crockford-style objects.

There also should be no sinerider-specific code in `Engine`, it's meant to be a content-agnostic abstraction that sets up the core event loops, instantiates `Screen`+`World`, and hooks up primitive events like key/mouse listeners. The content-specific stuff should all begin with `World.js`, the root of the entity tree.

This creates some weirdness because of all the sinerider-specific stuff happening in `main.js`, but we will finish cleaning that up later.

I probably overestimated how straightforward it would be to just swap `Engine.js` in over the mess in `main.js`. LMK if this feels like more of a headache than it's worth.

**Comment by grymmy** [comment]
Kk didn't realize there was a style requirement here - is this a hard rule vs prototypical inheritance?  Please instruct me on how to move forward here, I'd be absolutely fine going with something very small like my original diff that impacted very few lines and gets me mostly what I want, and I'd like to prioritize finishing and unblocking the backend services asap.

**Comment by polytroper** [comment]
Yeah, sadly this codebase is militantly anti-prototypes. Looking at your original diff now.

**Comment by polytroper** [comment]
Yeah, if the original diff works let's just go with that. When we upgrade the codebase to the vaunted ✨Engine 2✨ we will do all the Engine.js stuff.

**Comment by grymmy** [comment]
Closing this diff per discussion above.

**Pull request closed without merging**
