### PR TITLE
fix credits issues 

### PR DESCRIPTION
**Pull request by ClaireBookworm**
New edits in #462

### CODE REVIEW

**Comment by camdan-me** [comment]
🤔 this looks like it just reverted #525

**Comment by ClaireBookworm** [comment]
I dont think so? the edits should be there

**Comment by camdan-me** [comment]
This PR
image

525
image

This PR is missing me, polypixel, christina, max, and some additional thanks people

**Comment by ClaireBookworm** [comment]
oh huh wild — 525 is the correct new one!!

**Comment by ClaireBookworm** [comment]
OK WAIT im going to fix this!!

**Pull request merged**
