### PR TITLE
Differentiate cutscene levels from normal levels on map with rhombus shape

### LINKED ISSUE #218: [FEATURE] Differentiate Cutscenes from Levels on World Map
### Description
From HQ Playtest 3/9
Change the shape from Circles to Hexagons to make the differences more clear

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by polypixeldev**
This PR changes the shape of cutscene levels on the world map to a rhombus, which helps to differentiate them from normal levels.
I am not very familiar with vanilla JS gamedev or the Canvas API, any feedback is greatly appreciated.
Closes #218

### CODE REVIEW

**Comment by camdan-me** [comment]
Looks great, but what if they were like octagons? They feel a little small at the moment.

**Comment by polytroper** [comment]
Can we see what this looks like with squares? Even if it overlaps with the arrows for now, make them the same width as the circles.

**Comment by polypixeldev** [comment]
Here's an example of the octagon (I'm not what's the best way to get rid of the stroke overlap):
image

And an example of a square (i'm not sure why it feels smaller? I used the same polygon code as the octagon one, just with 4 sides instead of 8):
image

**Comment by camdan-me** [comment]
Looks like the square is the same size as the circle diagonally, for it to look the same size it needs to be the same size horizontally. Honestly though I'm a fan of the octagon, chris what do you think.

**Comment by polytroper** [comment]
Oh the octagon is pretty sweet. Go with that

**Comment by polypixeldev** [comment]
I changed it to an octogon but I'm having some trouble with the stroke. I can't figure out how to fix it to be continuous:
Screenshot from 2023-03-23 22-02-41

**Comment by polytroper** [comment]
You need to use `closePath`

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/closePath

**Comment by polypixeldev** [comment]
I am using closePath. It seems that the math is just not working out, because the last line is not ending out where the first line started:
image

**Comment by polytroper** [comment]
```
      ctx.beginPath()
      ctx.moveTo(radius, radius * Math.sin(0))

      for (var i = 1; i <= cutsceneFrameSides; i += 1) {                 <------ I think you want < here, not <=
        ctx.lineTo(
          (radius + strokeWidth / 2 - 0.02) *
            Math.cos((i * 2 * Math.PI) / cutsceneFrameSides),
          (radius + strokeWidth / 2 - 0.02) *
            Math.sin((i * 2 * Math.PI) / cutsceneFrameSides),
        )
      }
      ctx.closePath()
```

**Comment by polytroper** [comment]
Ignore me, that is not the problem

**Comment by polytroper** [comment]
Actually that was part of it, but not the full issue. On your initial call to `ctx.moveTo` you did not adjust for the stroke width, causing that vertex to be inset a little further than the rest

**Comment by polytroper** [comment]
This looks ready. Merging now

**Comment by polypixeldev** [comment]
Ah I see, thanks!

**Pull request merged**
