### PR TITLE
Add confirmation for show all button + some polish

### PR DESCRIPTION
**Pull request by Benjamin-Rosenfeld**
fixes issue #187

### CODE REVIEW

**Comment by Benjamin-Rosenfeld** [comment]
Now also fixes #417

**Comment by camdan-me** [comment]
Wasn't the plan for the show all button to be hidden in prod?

**Comment by Benjamin-Rosenfeld** [comment]
Really? In the issue it was decided to do a warning

**Comment by Benjamin-Rosenfeld** [comment]
fixes #398 and #427

**Comment by Benjamin-Rosenfeld** [comment]
@cwalker pls merge this has a lot of fixes now

**Comment by Benjamin-Rosenfeld** [comment]
So basically I got if off the old ui, and moved the changes to the new ui to that pr. Pls merge

**Comment by Benjamin-Rosenfeld** [comment]
fix #266

**Comment by polytroper** [comment]
This looks good, my only request is can we:
* get the text of the "Show All" button on the map changed to "Unlock All"
* change the "Show All" button in the dialogue to "Unlock"
* remove "This cannot be undone"

**Comment by polytroper** [comment]
Can you also make it so the dialog only pops up once, and once you say yes it stores a flag in local storage to prevent the dialog from appearing again

**Comment by polytroper** [comment]
How we doin here @Benjamin-Rosenfeld

**Comment by Benjamin-Rosenfeld** [comment]
sorry for the delay

**Comment by polytroper** [comment]
yay

**Pull request merged**
