### PR TITLE
added meta tags for twitter and facebook

### PR DESCRIPTION
**Pull request by brunoblaise**
Hey, I have added meta tags of 

- Twitter

- Facebook

and I have made `index.html` more readable by formatting it

### CODE REVIEW

**Comment by maxwofford** [comment]
This looks great, thanks @brunoblaise for the contribution!

Screen Shot 2022-08-24 at 08 42 12

A couple comments before we merge this in:
- The image is webp & it looks like [that might not always be supported](https://stackoverflow.com/a/57955712)– let's make a new file and call it something like `og_image.png` so we know it's just being used for the preview image.
- Looks like this also affects line wrapping and quotes for the whole file– that might have been some IDE formatter automatically changing things. Could you revert that? Happy to start a discussion about codebase styles, but that should be done in a separate PR.

**Comment by brunoblaise** [comment]
👌👌, Now I think everything is clear as you asked I changed the image to 

- [x] png 
- [x]  reverted the file to its original format

**Comment by maxwofford** [comment]
Hack yeah! Thanks so much :)

**Comment by brunoblaise** [comment]
You are welcome😊😊

**Comment by maxwofford** [comment]
@brunoblaise I think I have a couple left-over pre-production stickers & I'd be happy to ship you some for the PR– just send me the address I can send them to! My email is public on GitHub, or alternatively you can DM me on the [Hack Club Slack](https://hackclub.com/slack) (or #gamedev channel).

**Comment by maxwofford** [comment]
Also, we have a bunch of other tickets labeled ["good first issue"](https://github.com/hackclub/sinerider/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22) which should all help get acquainted with the codebase.

**Comment by brunoblaise** [comment]
I will be looking to all of them ("good first issue"
<https://github.com/hackclub/sinerider/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22>
)  and
thanks

**Pull request merged**
