### PR TITLE
Redesign UI

### PR DESCRIPTION
**Pull request by Captainexpo-1**
Issue #286, design changed in slack [thread](https://hackclub.slack.com/archives/C6LHL48G2/p1680370698887459)

Let me know if there are any bugs, or changes that need addressing.

Thank you!!!

### CODE REVIEW

**Comment by polytroper** [comment]
Let's clean up these logs
image

**Comment by polytroper** [comment]
Smaller vertical margins on the equation bar. Should match the margin seen on those buttons
image

**Comment by Captainexpo-1** [comment]
all fixed!

**Comment by polytroper** [comment]
Let's try this revision. 
IMG_8174

**Comment by camdan-me** [comment]
When you click start/stop, the fade animation is a little janky, you can see a sort of wireframe of the way you laid out the UI.

**Comment by polytroper** [comment]
Are those all formatting changes to `index.html`? If so remove all those changes to avoid merge conflict.s

**Comment by Captainexpo-1** [comment]
so every change i've made to it? @polytroper

**Comment by polytroper** [comment]
@Captainexpo-1 I'm so sorry I put that comment on the wrong PR! Please ignore

**Comment by camdan-me** [comment]
Not a fan of how the start/stop button teleports when clicked, is there another possible implementation there?

**Comment by Captainexpo-1** [comment]
it could just stay where it was, but then it would just be in a weird position around the middle/side of the screen, so I can't really think of anything else.

**Comment by camdan-me** [comment]
What if a play button hovered on the right side of the screen that turned into a timer when clicked?

**Comment by polytroper** [comment]
Have it stay where it was. It should be hovering outside the little bar down there, like in the drawing

**Comment by polytroper** [comment]
The UI will be balanced out by the timeline (see lower-right quadrant of whiteboard)

**Comment by polytroper** [comment]
Ok wow this is getting really close.

When the solution is running, can we try keeping everything in the same place? Keep the button bar and timeline on-screen, keep the t= button in the same spot. Make the little slider head bright red, and move it as the solution runs to show time. That way people know how it works when they get to the time levels. 

Disable the reset button when a solution is running. The other buttons can stay functional.

Let's also get rid of all the margins on those buttons (except the t= button, that one is fine as-is). No margins, shadows, or border radius on elements inside the toolbar, sink the buttons directly into the bar.

Nice job this is really coming along.

**Comment by Captainexpo-1** [comment]
The time slider could also only be active when the user uses time in their equation.

**Comment by polytroper** [comment]
I think it's important that the timeline appear from the start to convey it's purpose. The time slider is not an easy mechanic for people to wrap their heads around, introducing it passively and immediately is our only hope for communicating the relationship of that slider to the equations in the time levels

**Comment by polytroper** [comment]
The t= button still moves. Keep it in the same place when the solution starts running.

Continue the slider off-screen a bit so that the red dot doesn't appear to get stuck at t=10.

Let's do away with the transparency effect on that equation bar when the solution starts running,

Also repeating this feedback from the comment above:
> Let's also get rid of all the margins on those buttons (except the t= button, that one is fine as-is). No margins, shadows, or border radius on elements inside the toolbar, sink the buttons directly into the bar.
Our goal is to have those controls be super low-profile.

**Comment by polypixeldev** [comment]
The new UI seems to glitch on the constant lake cutscene:
image

**Comment by polypixeldev** [comment]
The try again button (when you hit the wrong order goal first) also doesn't go away when you click on it, and keeps flashing - I expected it to go away when I clicked on it.

**Comment by polytroper** [comment]
Timeline should be responsive to the size of the button. 

image

Screenshot 2023-04-09 at 6 22 59 PM

Victory screen needs to be above timeline

Screenshot 2023-04-09 at 6 23 58 PM

Whole bar needs to turn gray

image

**Comment by camdan-me** [comment]
The timeline feels a little confusing this early in the game since dragging it doesn't actually run the physics simulation. I know it'll become clearer later, but the way it's introduced is confusing.

**Comment by Benjamin-Rosenfeld** [comment]
Just an idea, but maybe you can add a Tip which explains the time slider a bit

**Comment by polytroper** [comment]
How about this, the timeline shows while the simulation is running if you are not using `t` in your solution but it will show all the time if you are using `t`

**Comment by polytroper** [comment]
And yes we will def need a tooltip thank you @Benjamin-Rosenfeld

**Comment by polytroper** [comment]
This upper border radius size needs to be responsive to the equation box size, like the lower one

image

**Comment by cytronicoder** [comment]
Just a minor thing, but can we add some space between the time line and the start button?
Screenshot 2023-04-10 at 10 39 30 PM

Additionally, some times the time line might not be viewable against the ground - is that possible to manually configure for each round?

**Comment by polytroper** [comment]
> Just a minor thing, but can we add some space between the time line and the start button? Screenshot 2023-04-10 at 10 39 30 PM
> 
> Additionally, some times the time line might not be viewable against the ground - is that possible to manually configure for each round?
> 
> Otherwise, this looks great! Much thanks to @Captainexpo-1 for working on this redesign ❤️

@cytronicoder The timeline needs to be responsive to the size of the t= button since it changes as the solution runs.

Timeline also needs to adopt additional contrast elements to always be visible. Similar to the tooltips, which have a white BG and thick black border. Maybe something similar for timeline is in order?

**Comment by alhardwarehyde** [comment]
Related to #201 -at minimum replace the files with images of the emoji.

**Comment by alhardwarehyde** [comment]
Also #266

**Comment by polytroper** [comment]
Whoops. Accidentally committed some changes in here that were meant for main. I don't have time for git surgery, I will just leave them in here to be merged in with the UI.

**Comment by polytroper** [comment]
Instead of a white gradient poof behind each timeline number, let's give them a solid white (or off-white, like #DDD) backing. Circular or heavily rounded. And let's make the timeline itself white

**Comment by polytroper** [comment]
We need a graceful way for the controls to exist on the screen without the equation (for example, in the cutscenes). I propose sliding out from the left side. By sliding that whole UI left/right you can show the whole thing, just the controls, just the controls, or nothing at all.

**Comment by polytroper** [comment]
Currently nothing clickable on ui D:

**Comment by Captainexpo-1** [comment]
@polytroper
 On mobile, should the time-slider layout look something like this? 
t-slider-mobile-concept

**Comment by polytroper** [comment]
Many parts of this are still obviously broken but I am merging because yolo

**Comment by camdan-me** [comment]
Move fast and break things

**Pull request merged**
