### PR TITLE
feat: Add Redirect to Reddit Thread

### PR DESCRIPTION
**Pull request by GalaxyGamingBoy**
The user is prompted to redirect to the reddit thread after puzzle completion.

### CODE REVIEW

**Comment by GalaxyGamingBoy** [comment]
Must be resolved alongside:
https://github.com/hackclub/sinerider-api/pull/13

**Comment by GalaxyGamingBoy** [comment]
Fixes issue #523

**Comment by polytroper** [comment]
Please do not submit autoformat changes in PRs, it makes them very hard to review.

**Comment by GalaxyGamingBoy** [comment]
@polytroper I believe the commit with the autoformat changes was to update the fork to latest

**Pull request merged**
